version: "3.7"
services:
  php:
    container_name: product_recommendation
    image: product_recommendation_php
    build:
      context: ./app/
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 9000
    volumes:
      - ./app:/app

  nginx:
    container_name: product_recommendation_nginx
    image: product_recommendation_nginx
    build:
      context: ./app/docker/nginx
      dockerfile: ./Dockerfile
    links:
      - php
    ports:
      - 8080:80
      - 443:443
    volumes:
      - "./app/public:/var/www/app/public"
    environment:
      - API_HOST=php
      - API_PORT=9000