version: "3.7"
services:
  php:
    container_name: product_recommendation
    image: product_recommendation_php
    build:
      context: ./app/
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 9000
    volumes:
      - ./app:/app
    environment:
      - DB_SERVER=mysql
      - DATABASE_URL=mysql
      - DB_PORT=3306
      - DB_NAME=app
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - mysql

  mysql:
    container_name: product_recommendation_database
    image: mysql:8.0.37
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app

  nginx:
    container_name: product_recommendation_nginx
    image: product_recommendation_nginx
    build:
      context: ./app/docker/nginx
      dockerfile: ./Dockerfile
    links:
      - php
    ports:
      - 8080:80
      - 443:443
    volumes:
      - "./app/public:/var/www/app/public"
    environment:
      - API_HOST=php
      - API_PORT=9000